### ISSUE TITLE
USER STORY: write testimonials

### ISSUE THREAD

**Issue by nils-n** [nils-n/keep-walking#12]
As a website user I can write a testimonial in my personal area so that I can express my opinion about the website to other users

## Acceptance Criteria: 

-  After login, the user can write a testimonial in his 
-  After reviewing, the admin can either reject or approve the testimonial
- After approving, the testimonial should be visible on the main page 

## Tasks:
- [ ] Create server-side CRUD mechanics for testimonials 
- [ ] Add forms to front-end for user access these CRUD methods from the website by clicking buttons and filling out a form
- [ ] Add appropriate messages to user, such as confirming to delete or if empty form was submitted
