### ISSUE TITLE
USER STORY: Logout

### ISSUE THREAD

**Issue by nils-n** [nils-n/keep-walking#3]
As a **signed in website user** I can **click on the logout button** so that **I  sign out of my personal area and close the website**

## Acceptance Criteria: 

-  After login, the user can see and click on a 'logout' button 
- After clicking on logout button, user is redirected to main page and logged out
- The personal area should now not be accessible any more 

## Tasks:
- [x] Implement Logout functionality on server side (django)
- [x] Add Logout buttons to page/navbar and add event listener 
- [x] Visual Feedback (such as message or modal) that logout was successful
