### ISSUE TITLE
USER STORY: View Health Stats 

### ISSUE THREAD

**Issue by nils-n** [nils-n/keep-walking#4]
As a signed in user I can view my step count and weight measurements of the recent time so that I am motivated to moving more and be on a good way of maintaining or reaching a healthy BMI (Body-mass-index)

## Acceptance Criteria: 

-  User goes to personal area and can see a list of this daily stats 
- User can choose a time range where (i.e. pagination with each page a month)
- If not synced with the Garmin watch, the user sees the option to sync with their watch 
- when clicking on the sync button, the activities should be loaded 
- when the user signs in again, the data should still be there without syncing again 

## Tasks:

- [x] Implement back-end access for accessing DB where Garmin data is stored 
- [x] Implement front-end display of the data, such as lists, cards or diagrams 
- [x] calculate BMI based on weight, height and age
- [x] summarize health stats at the main dashboard based on user data
- [x] add a plot to show last 30 days of walking
- [x] add a plot to show last 30 days of BMI and linear trend of BMI 
- [x] add a plot to show last 30 days of body weight (kg) and linear trend of body weight (kg)
