### ISSUE TITLE
USER STORY: Give Emotional Rating

### ISSUE THREAD

**Issue by nils-n** [nils-n/keep-walking#5]
As a signed in user I can give an emotional rating for each day so that (over time) I can find out whether increasing daily walks leads to increased happiness

## Acceptance Criteria: 

-  When an activity of a day is displayed, the user can express how they felt on that day 
- This can be achieved i.e. by clicking on emojis/smileys (happy - neutral - bad) 
- When clicking on of the smileys, it should be visually clear what the rating was 
- If there was already a rating for that day, the user is able to change it retrospectively 

## Tasks:

- [x] Implement back-end CRUD for Emotional Rating 
- [x] Implement front-end display of rating 
- [x] add intuitive front-end display of rating that allows user to edit the rating
- [x] Visual Feedback or message to user when edit or delete was successful
