### ISSUE TITLE
USER STORY: Load health data from Garmin watch

### ISSUE THREAD

**Issue by nils-n** [nils-n/keep-walking#7]
As a signed in user I can load my health stats from my Garmin watch so that (over time) I can track my exact step count and my weight measurements from the Garmin App 

## Acceptance Criteria: 

-  User can retrieve data from the Garmin API via clicking a button
- New data will be loaded and visible in the personal area (including a time stamp informing when was last sync)

## Tasks:
- [x] Implement back-end to access selected stats from Garmin API 
- [x] Implement front-end display 
    - [x] Display of recent daily activity  (steps, weight) so that user gets feedback about their step and weight goal in a playful/motivating way
    - [x] user can choose different time ranges, such as last month or current month. In this way , the user gets feedback if their health stats have improved since they started meeting their daily walking goal
    - [x] Visual Feedback or message to user when syncing with Garmin was successful
- [x]  Interpolate missing entries for weights (instead of displaying 0 kg ). Can be simple linear interpolation. 
- [x] Update summary text below diagram according to progress (for example, improving BMI over last month triggers positive and encouraging message. Worsening BMI triggers motivational message)
    - [x] Update summary message for BMI and BMI trend based on recent 30 days
    - [x] Update  weight  summary based on recent 30 days 
    - [x] Update  summary of emotional rating based on recent 30 days 
- [x] (Optional) Draw stepcount and weight in a diagram using a javascript library
