### ISSUE TITLE
USER STORY: Create, Edit and Delete Garmin stats

### ISSUE THREAD

**Issue by nils-n** [nils-n/keep-walking#8]
As a signed in user I can view, edit and delete my Garmin stats for each day so that I can correct a wrong reading (such as a wrong manual entry of weight in the App), or delete my records from the database 

## Acceptance Criteria: 

- User goes to personal area and can see a list of their health stats 
- User can click on a button of each activity to modify or delete activity
- when clicking on the edit button, a form should be loaded to change the data stored for that data entry
   - when clicking submit after editing, the change should be reflected on the list and the stats updated accordingly
- when clicking on the delete button, the user should receive a dialog that this action cannot be undone 
  - when canceling the delete operation, the activity should persist
  - when confirming the delete operation, the activity should be removed from the list
- if a user has no garmin watch, they should still be able to track their walks and weight manually
  -  add optional form to enter weight + steps +   date manually into the DB 
  - manually entering should be rendered immediately after rendering (no reloading of the page - use htmx for that)

## Tasks:
- [x] Implement back-end CRUD for Garmin data
- [x] Implement front-end display 
- [x] Display of health stats and buttons for edit and delete 
- [x] Forms to edit current values (such as weight measurement of that data item)
- [x] Visual Feedback or message to user when edit or delete was successful
- [x] add option to manually add entries for users that do not own a Garmin watch (or from a different brand)
